    version: '3.5'
    
    services:
      postgres:
        image: postgres:14.1-alpine
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
        volumes:
          - postgres:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped
    
      pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        ports:
          - "8081:80"
        depends_on:
          - postgres
        networks:
          - postgres
    
    networks:
      postgres:
        driver: bridge
    
    volumes:
        postgres:
